/**
 * Mapper Unit Tests
 *
 * Tests the type mappers that convert between Drizzle and Core types.
 */
import { describe, expect, it } from 'vitest';
import { mapCoreCustomerCreateToDrizzle, mapDrizzleCustomerToCore } from '../src/mappers/customer.mapper.js';
import { mapDrizzlePaymentToCore } from '../src/mappers/payment.mapper.js';
import { mapCorePlanCreateToDrizzle, mapDrizzlePlanToCore } from '../src/mappers/plan.mapper.js';
import { mapCoreSubscriptionCreateToDrizzle, mapDrizzleSubscriptionToCore } from '../src/mappers/subscription.mapper.js';
import type { QZPayBillingCustomer } from '../src/schema/customers.schema.js';
import type { QZPayBillingPayment } from '../src/schema/payments.schema.js';
import type { QZPayBillingPlan } from '../src/schema/plans.schema.js';
import type { QZPayBillingSubscription } from '../src/schema/subscriptions.schema.js';

describe('Customer Mapper', () => {
    describe('mapDrizzleCustomerToCore', () => {
        it('should map basic customer fields', () => {
            const drizzleCustomer: QZPayBillingCustomer = {
                id: 'cust-123',
                externalId: 'ext-123',
                email: 'test@example.com',
                name: 'Test User',
                stripeCustomerId: null,
                mpCustomerId: null,
                preferredLanguage: 'en',
                segment: 'premium',
                tier: null,
                billingAddress: {},
                shippingAddress: null,
                taxId: null,
                taxIdType: null,
                livemode: true,
                metadata: { foo: 'bar' },
                version: 'v1',
                createdAt: new Date('2024-01-01'),
                updatedAt: new Date('2024-01-02'),
                deletedAt: null
            };

            const core = mapDrizzleCustomerToCore(drizzleCustomer);

            expect(core.id).toBe('cust-123');
            expect(core.externalId).toBe('ext-123');
            expect(core.email).toBe('test@example.com');
            expect(core.name).toBe('Test User');
            expect(core.livemode).toBe(true);
            expect(core.metadata).toEqual({ foo: 'bar' });
            expect(core.createdAt).toEqual(new Date('2024-01-01'));
            expect(core.updatedAt).toEqual(new Date('2024-01-02'));
        });

        it('should map provider customer IDs', () => {
            const drizzleCustomer: QZPayBillingCustomer = {
                id: 'cust-456',
                externalId: 'ext-456',
                email: 'provider@example.com',
                name: null,
                stripeCustomerId: 'cus_stripe123',
                mpCustomerId: 'mp_customer456',
                preferredLanguage: null,
                segment: null,
                tier: null,
                billingAddress: {},
                shippingAddress: null,
                taxId: null,
                taxIdType: null,
                livemode: true,
                metadata: {},
                version: 'v1',
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            const core = mapDrizzleCustomerToCore(drizzleCustomer);

            expect(core.providerCustomerIds).toEqual({
                stripe: 'cus_stripe123',
                mercadopago: 'mp_customer456'
            });
        });

        it('should handle null name', () => {
            const drizzleCustomer: QZPayBillingCustomer = {
                id: 'cust-789',
                externalId: 'ext-789',
                email: 'nullname@example.com',
                name: null,
                stripeCustomerId: null,
                mpCustomerId: null,
                preferredLanguage: null,
                segment: null,
                tier: null,
                billingAddress: {},
                shippingAddress: null,
                taxId: null,
                taxIdType: null,
                livemode: true,
                metadata: {},
                version: 'v1',
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null
            };

            const core = mapDrizzleCustomerToCore(drizzleCustomer);

            // Mapper returns null for null name, not undefined
            expect(core.name).toBeNull();
        });
    });

    describe('mapCoreCustomerCreateToDrizzle', () => {
        it('should map core create input to drizzle insert', () => {
            const coreInput = {
                externalId: 'ext-new-1',
                email: 'new@example.com',
                name: 'New User',
                metadata: { source: 'api' }
            };

            const drizzle = mapCoreCustomerCreateToDrizzle(coreInput, true);

            // Note: id is not included in insert - it's auto-generated by database
            expect(drizzle.externalId).toBe('ext-new-1');
            expect(drizzle.email).toBe('new@example.com');
            expect(drizzle.name).toBe('New User');
            expect(drizzle.livemode).toBe(true);
            expect(drizzle.metadata).toEqual({ source: 'api' });
        });

        it('should set livemode based on parameter', () => {
            const coreInput = {
                externalId: 'ext-test-1',
                email: 'test@example.com'
            };

            const live = mapCoreCustomerCreateToDrizzle(coreInput, true);
            const test = mapCoreCustomerCreateToDrizzle(coreInput, false);

            expect(live.livemode).toBe(true);
            expect(test.livemode).toBe(false);
        });
    });
});

describe('Subscription Mapper', () => {
    describe('mapDrizzleSubscriptionToCore', () => {
        it('should map subscription with all fields', () => {
            const now = new Date();
            const periodEnd = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

            const drizzleSub: QZPayBillingSubscription = {
                id: 'sub-123',
                customerId: 'cust-123',
                planId: 'plan-123',
                priceId: null,
                status: 'active',
                billingInterval: 'month',
                intervalCount: 1,
                currentPeriodStart: now,
                currentPeriodEnd: periodEnd,
                trialStart: null,
                trialEnd: null,
                cancelAt: null,
                canceledAt: null,
                promoCodeId: null,
                stripeSubscriptionId: 'sub_stripe123',
                mpSubscriptionId: null,
                billingRetryCount: 0,
                nextBillingRetryAt: null,
                livemode: true,
                metadata: {},
                version: 'v1',
                createdAt: now,
                updatedAt: now,
                deletedAt: null
            };

            const core = mapDrizzleSubscriptionToCore(drizzleSub);

            expect(core.id).toBe('sub-123');
            expect(core.customerId).toBe('cust-123');
            expect(core.planId).toBe('plan-123');
            expect(core.status).toBe('active');
            // Core uses 'interval' not 'billingInterval'
            expect(core.interval).toBe('month');
            expect(core.intervalCount).toBe(1);
            expect(core.currentPeriodStart).toEqual(now);
            expect(core.currentPeriodEnd).toEqual(periodEnd);
            expect(core.providerSubscriptionIds).toEqual({ stripe: 'sub_stripe123' });
        });

        it('should handle trial dates', () => {
            const now = new Date();
            const trialEnd = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);

            const drizzleSub: QZPayBillingSubscription = {
                id: 'sub-trial',
                customerId: 'cust-123',
                planId: 'plan-123',
                priceId: null,
                status: 'trialing',
                billingInterval: 'month',
                intervalCount: 1,
                currentPeriodStart: now,
                currentPeriodEnd: trialEnd,
                trialStart: now,
                trialEnd: trialEnd,
                cancelAt: null,
                canceledAt: null,
                promoCodeId: null,
                stripeSubscriptionId: null,
                mpSubscriptionId: null,
                billingRetryCount: 0,
                nextBillingRetryAt: null,
                livemode: true,
                metadata: {},
                version: 'v1',
                createdAt: now,
                updatedAt: now,
                deletedAt: null
            };

            const core = mapDrizzleSubscriptionToCore(drizzleSub);

            expect(core.trialStart).toEqual(now);
            expect(core.trialEnd).toEqual(trialEnd);
        });
    });

    describe('mapCoreSubscriptionCreateToDrizzle', () => {
        it('should map create input with defaults', () => {
            const now = new Date();
            const periodEnd = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

            const coreInput = {
                id: 'new-sub-1',
                customerId: 'cust-123',
                planId: 'plan-123'
            };

            const defaults = {
                livemode: true,
                billingInterval: 'month',
                intervalCount: 1,
                currentPeriodStart: now,
                currentPeriodEnd: periodEnd
            };

            const drizzle = mapCoreSubscriptionCreateToDrizzle(coreInput, defaults);

            expect(drizzle.id).toBe('new-sub-1');
            expect(drizzle.customerId).toBe('cust-123');
            expect(drizzle.planId).toBe('plan-123');
            expect(drizzle.status).toBe('active');
            expect(drizzle.livemode).toBe(true);
            expect(drizzle.billingInterval).toBe('month');
        });
    });
});

describe('Payment Mapper', () => {
    describe('mapDrizzlePaymentToCore', () => {
        it('should map payment with all fields', () => {
            const now = new Date();

            const drizzlePayment: QZPayBillingPayment = {
                id: 'pay-123',
                customerId: 'cust-123',
                subscriptionId: 'sub-123',
                invoiceId: null,
                amount: 9999,
                currency: 'USD',
                baseAmount: null,
                baseCurrency: null,
                exchangeRate: null,
                status: 'succeeded',
                provider: 'stripe',
                providerPaymentId: 'pi_stripe123',
                paymentMethodId: null,
                refundedAmount: 0,
                failureCode: null,
                failureMessage: null,
                idempotencyKey: 'idem-123',
                livemode: true,
                metadata: {},
                version: 'v1',
                createdAt: now,
                updatedAt: now,
                deletedAt: null
            };

            const core = mapDrizzlePaymentToCore(drizzlePayment);

            expect(core.id).toBe('pay-123');
            expect(core.customerId).toBe('cust-123');
            expect(core.subscriptionId).toBe('sub-123');
            expect(core.amount).toBe(9999);
            expect(core.currency).toBe('USD');
            expect(core.status).toBe('succeeded');
            // Provider is mapped to providerPaymentIds
            expect(core.providerPaymentIds).toEqual({ stripe: 'pi_stripe123' });
        });

        it('should handle failed payment', () => {
            const now = new Date();

            const drizzlePayment: QZPayBillingPayment = {
                id: 'pay-failed',
                customerId: 'cust-123',
                subscriptionId: null,
                invoiceId: null,
                amount: 5000,
                currency: 'USD',
                baseAmount: null,
                baseCurrency: null,
                exchangeRate: null,
                status: 'failed',
                provider: 'stripe',
                providerPaymentId: null,
                paymentMethodId: null,
                refundedAmount: 0,
                failureCode: 'card_declined',
                failureMessage: 'Your card was declined',
                idempotencyKey: null,
                livemode: true,
                metadata: {},
                version: 'v1',
                createdAt: now,
                updatedAt: now,
                deletedAt: null
            };

            const core = mapDrizzlePaymentToCore(drizzlePayment);

            expect(core.status).toBe('failed');
            expect(core.failureCode).toBe('card_declined');
            expect(core.failureMessage).toBe('Your card was declined');
        });
    });
});

describe('Plan Mapper', () => {
    describe('mapDrizzlePlanToCore', () => {
        it('should map plan with all fields', () => {
            const now = new Date();

            const drizzlePlan: QZPayBillingPlan = {
                id: 'plan-123',
                name: 'Pro Plan',
                description: 'Professional features',
                active: true,
                features: [
                    { name: 'Feature 1', included: true },
                    { name: 'Feature 2', included: true, limit: '100/month' }
                ],
                entitlements: ['feature_1', 'feature_2'],
                limits: { api_calls: 10000 },
                metadata: { tier: 'pro' },
                livemode: true,
                version: 'v1',
                createdAt: now,
                updatedAt: now,
                deletedAt: null
            };

            const core = mapDrizzlePlanToCore(drizzlePlan, []);

            expect(core.id).toBe('plan-123');
            expect(core.name).toBe('Pro Plan');
            expect(core.description).toBe('Professional features');
            expect(core.active).toBe(true);
            expect(core.features).toHaveLength(2);
            expect(core.entitlements).toEqual(['feature_1', 'feature_2']);
            expect(core.limits).toEqual({ api_calls: 10000 });
        });

        it('should handle inactive plan', () => {
            const now = new Date();

            const drizzlePlan: QZPayBillingPlan = {
                id: 'plan-inactive',
                name: 'Legacy Plan',
                description: null,
                active: false,
                features: [],
                entitlements: [],
                limits: {},
                metadata: {},
                livemode: true,
                version: 'v1',
                createdAt: now,
                updatedAt: now,
                deletedAt: null
            };

            const core = mapDrizzlePlanToCore(drizzlePlan, []);

            expect(core.active).toBe(false);
            // Mapper returns null for null description, not undefined
            expect(core.description).toBeNull();
        });
    });

    describe('mapCorePlanCreateToDrizzle', () => {
        it('should map create input', () => {
            const coreInput = {
                id: 'new-plan-1',
                name: 'New Plan',
                description: 'A new plan',
                features: [{ name: 'Feature', included: true }],
                entitlements: ['feature'],
                limits: { limit: 100 }
            };

            const drizzle = mapCorePlanCreateToDrizzle(coreInput, true);

            expect(drizzle.id).toBe('new-plan-1');
            expect(drizzle.name).toBe('New Plan');
            expect(drizzle.description).toBe('A new plan');
            expect(drizzle.livemode).toBe(true);
            expect(drizzle.active).toBe(true);
        });
    });
});
