#!/bin/bash
# Claude Code notification hook
# Generated by @qazuor/claude-code-config

MESSAGE="${1:-Claude needs your attention}"

# Desktop notification
if command -v notify-send &> /dev/null; then
  notify-send "Claude Code" "$MESSAGE" --icon=dialog-information
elif command -v terminal-notifier &> /dev/null; then
  terminal-notifier -title "Claude Code" -message "$MESSAGE"
elif command -v osascript &> /dev/null; then
  osascript -e "display notification \"$MESSAGE\" with title \"Claude Code\""
fi

# Audio notification (text-to-speech)
if command -v piper &> /dev/null; then
  echo "$MESSAGE" | piper --model ~/.local/share/piper/voices/en_US-hfc_male-medium.onnx --output-raw | aplay -r 22050 -f S16_LE -t raw - 2>/dev/null
elif command -v say &> /dev/null; then
  say "$MESSAGE"
elif command -v espeak &> /dev/null; then
  espeak "$MESSAGE"
fi
