#!/bin/bash
# Claude Code stop hook
# Generated by @qazuor/claude-code-config

# Play beep sound
if command -v aplay &> /dev/null; then
  # Generate a beep using speaker-test or beep command
  ( speaker-test -t sine -f 1000 -l 1 ) &>/dev/null & pid=$!; sleep 0.2; kill -9 $pid &>/dev/null
elif command -v afplay &> /dev/null; then
  afplay /System/Library/Sounds/Glass.aiff
elif command -v powershell.exe &> /dev/null; then
  powershell.exe -c "[console]::beep(1000,200)"
else
  printf "\a"
fi
