#!/bin/bash
# Claude Code subagent stop hook
# Generated by @qazuor/claude-code-config

# Play short beep
if command -v aplay &> /dev/null; then
  ( speaker-test -t sine -f 800 -l 1 ) &>/dev/null & pid=$!; sleep 0.1; kill -9 $pid &>/dev/null
elif command -v afplay &> /dev/null; then
  afplay /System/Library/Sounds/Pop.aiff
else
  printf "\a"
fi
