/**
 * Currency constants (ISO 4217)
 */
export const QZPAY_CURRENCY = {
    USD: 'USD',
    EUR: 'EUR',
    GBP: 'GBP',
    ARS: 'ARS',
    BRL: 'BRL',
    MXN: 'MXN',
    CLP: 'CLP',
    COP: 'COP',
    PEN: 'PEN',
    UYU: 'UYU'
} as const;

export type QZPayCurrency = (typeof QZPAY_CURRENCY)[keyof typeof QZPAY_CURRENCY];

export const QZPAY_CURRENCY_VALUES = Object.values(QZPAY_CURRENCY) as readonly QZPayCurrency[];

/**
 * ISO 4217 currency codes (comprehensive list).
 *
 * This set contains all valid 3-letter currency codes according to ISO 4217 standard.
 * Used for validation to ensure only real currency codes are accepted.
 *
 * Source: ISO 4217 standard - https://www.iso.org/iso-4217-currency-codes.html
 *
 * @internal
 */
export const ISO_4217_CURRENCY_CODES = new Set<string>([
    'AED',
    'AFN',
    'ALL',
    'AMD',
    'ANG',
    'AOA',
    'ARS',
    'AUD',
    'AWG',
    'AZN',
    'BAM',
    'BBD',
    'BDT',
    'BGN',
    'BHD',
    'BIF',
    'BMD',
    'BND',
    'BOB',
    'BOV',
    'BRL',
    'BSD',
    'BTN',
    'BWP',
    'BYN',
    'BZD',
    'CAD',
    'CDF',
    'CHE',
    'CHF',
    'CHW',
    'CLF',
    'CLP',
    'CNY',
    'COP',
    'COU',
    'CRC',
    'CUC',
    'CUP',
    'CVE',
    'CZK',
    'DJF',
    'DKK',
    'DOP',
    'DZD',
    'EGP',
    'ERN',
    'ETB',
    'EUR',
    'FJD',
    'FKP',
    'GBP',
    'GEL',
    'GHS',
    'GIP',
    'GMD',
    'GNF',
    'GTQ',
    'GYD',
    'HKD',
    'HNL',
    'HRK',
    'HTG',
    'HUF',
    'IDR',
    'ILS',
    'INR',
    'IQD',
    'IRR',
    'ISK',
    'JMD',
    'JOD',
    'JPY',
    'KES',
    'KGS',
    'KHR',
    'KMF',
    'KPW',
    'KRW',
    'KWD',
    'KYD',
    'KZT',
    'LAK',
    'LBP',
    'LKR',
    'LRD',
    'LSL',
    'LYD',
    'MAD',
    'MDL',
    'MGA',
    'MKD',
    'MMK',
    'MNT',
    'MOP',
    'MRU',
    'MUR',
    'MVR',
    'MWK',
    'MXN',
    'MXV',
    'MYR',
    'MZN',
    'NAD',
    'NGN',
    'NIO',
    'NOK',
    'NPR',
    'NZD',
    'OMR',
    'PAB',
    'PEN',
    'PGK',
    'PHP',
    'PKR',
    'PLN',
    'PYG',
    'QAR',
    'RON',
    'RSD',
    'RUB',
    'RWF',
    'SAR',
    'SBD',
    'SCR',
    'SDG',
    'SEK',
    'SGD',
    'SHP',
    'SLE',
    'SLL',
    'SOS',
    'SPL',
    'SRD',
    'STN',
    'SYP',
    'SZL',
    'THB',
    'TJS',
    'TMT',
    'TND',
    'TOP',
    'TRY',
    'TTD',
    'TVD',
    'TWD',
    'TZS',
    'UAH',
    'UGX',
    'USD',
    'USN',
    'UYI',
    'UYU',
    'UYW',
    'UZS',
    'VED',
    'VES',
    'VND',
    'VUV',
    'WST',
    'XAF',
    'XAG',
    'XAU',
    'XBA',
    'XBB',
    'XBC',
    'XBD',
    'XCD',
    'XDR',
    'XOF',
    'XPD',
    'XPF',
    'XPT',
    'XSU',
    'XTS',
    'XUA',
    'XXX',
    'YER',
    'ZAR',
    'ZMW',
    'ZWL'
]);

/**
 * Validate if a string is a valid ISO 4217 currency code.
 *
 * @param currency - Currency code to validate (case-insensitive)
 * @returns True if the currency code is valid according to ISO 4217
 *
 * @example
 * ```ts
 * qzpayIsValidIso4217Currency('USD') // true
 * qzpayIsValidIso4217Currency('eur') // true
 * qzpayIsValidIso4217Currency('XXX') // true (valid as "no currency" code)
 * qzpayIsValidIso4217Currency('FAKE') // false
 * ```
 */
export function qzpayIsValidIso4217Currency(currency: string): boolean {
    return ISO_4217_CURRENCY_CODES.has(currency.toUpperCase());
}
